### PR TITLE
Typo in readme

### PR DESCRIPTION
**Pull request by AlirezaAbd-dev**
Do not make this mistake again or i will make you piss your pants yet and after.

### CODE REVIEW

**Comment by shervinbdndev** [comment]
That was such kindness of you brother.
thank you♥️

**Comment by AlirezaAbd-dev** [comment]
Don't mention it

**Comment by AlirezaAbd-dev** [comment]
With all my heart & love

**Review by AlirezaAbd-dev — COMMENTED** [review]
I don't know what a review is XDD

**Review by AlirezaAbd-dev — COMMENTED** [review]
I know now

**Pull request merged**
